/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContratarConfirmacionRouteImport } from './routes/contratar.confirmacion'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedMiProgresoRouteImport } from './routes/_authenticated/mi-progreso'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContratarExpertoRouteImport } from './routes/_authenticated/contratar-experto'
import { Route as AuthenticatedSolutionsIndexRouteImport } from './routes/_authenticated/solutions.index'
import { Route as AuthenticatedMentoriaIndexRouteImport } from './routes/_authenticated/mentoria.index'
import { Route as AuthenticatedImplementadorIndexRouteImport } from './routes/_authenticated/implementador.index'
import { Route as AuthenticatedCursosIndexRouteImport } from './routes/_authenticated/cursos.index'
import { Route as AuthenticatedBuilderIndexRouteImport } from './routes/_authenticated/builder.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as SolutionsIdContratarRouteImport } from './routes/solutions.$id.contratar'
import { Route as AuthenticatedSolutionsSlugRouteImport } from './routes/_authenticated/solutions.$slug'
import { Route as AuthenticatedSolutionsIdRouteImport } from './routes/_authenticated/solutions.$id'
import { Route as AuthenticatedCursosCourseIdRouteImport } from './routes/_authenticated/cursos.$courseId'
import { Route as AuthenticatedAdminCursosIndexRouteImport } from './routes/_authenticated/admin.cursos.index'
import { Route as AuthenticatedImplementadorProyectoProjectIdRouteImport } from './routes/_authenticated/implementador.proyecto.$projectId'
import { Route as AuthenticatedAdminCursosCourseIdRouteImport } from './routes/_authenticated/admin.cursos.$courseId'
import { Route as AuthenticatedCursosCourseIdLeccionLessonIdRouteImport } from './routes/_authenticated/cursos.$courseId.leccion.$lessonId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratarConfirmacionRoute = ContratarConfirmacionRouteImport.update({
  id: '/contratar/confirmacion',
  path: '/contratar/confirmacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMiProgresoRoute = AuthenticatedMiProgresoRouteImport.update({
  id: '/mi-progreso',
  path: '/mi-progreso',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContratarExpertoRoute =
  AuthenticatedContratarExpertoRouteImport.update({
    id: '/contratar-experto',
    path: '/contratar-experto',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSolutionsIndexRoute =
  AuthenticatedSolutionsIndexRouteImport.update({
    id: '/solutions/',
    path: '/solutions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMentoriaIndexRoute =
  AuthenticatedMentoriaIndexRouteImport.update({
    id: '/mentoria/',
    path: '/mentoria/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImplementadorIndexRoute =
  AuthenticatedImplementadorIndexRouteImport.update({
    id: '/implementador/',
    path: '/implementador/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCursosIndexRoute =
  AuthenticatedCursosIndexRouteImport.update({
    id: '/cursos/',
    path: '/cursos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBuilderIndexRoute =
  AuthenticatedBuilderIndexRouteImport.update({
    id: '/builder/',
    path: '/builder/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SolutionsIdContratarRoute = SolutionsIdContratarRouteImport.update({
  id: '/solutions/$id/contratar',
  path: '/solutions/$id/contratar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSolutionsSlugRoute =
  AuthenticatedSolutionsSlugRouteImport.update({
    id: '/solutions/$slug',
    path: '/solutions/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSolutionsIdRoute =
  AuthenticatedSolutionsIdRouteImport.update({
    id: '/solutions/$id',
    path: '/solutions/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCursosCourseIdRoute =
  AuthenticatedCursosCourseIdRouteImport.update({
    id: '/cursos/$courseId',
    path: '/cursos/$courseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCursosIndexRoute =
  AuthenticatedAdminCursosIndexRouteImport.update({
    id: '/admin/cursos/',
    path: '/admin/cursos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImplementadorProyectoProjectIdRoute =
  AuthenticatedImplementadorProyectoProjectIdRouteImport.update({
    id: '/implementador/proyecto/$projectId',
    path: '/implementador/proyecto/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCursosCourseIdRoute =
  AuthenticatedAdminCursosCourseIdRouteImport.update({
    id: '/admin/cursos/$courseId',
    path: '/admin/cursos/$courseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCursosCourseIdLeccionLessonIdRoute =
  AuthenticatedCursosCourseIdLeccionLessonIdRouteImport.update({
    id: '/leccion/$lessonId',
    path: '/leccion/$lessonId',
    getParentRoute: () => AuthenticatedCursosCourseIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/contratar-experto': typeof AuthenticatedContratarExpertoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mi-progreso': typeof AuthenticatedMiProgresoRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/contratar/confirmacion': typeof ContratarConfirmacionRoute
  '/cursos/$courseId': typeof AuthenticatedCursosCourseIdRouteWithChildren
  '/solutions/$id': typeof AuthenticatedSolutionsIdRoute
  '/solutions/$slug': typeof AuthenticatedSolutionsSlugRoute
  '/solutions/$id/contratar': typeof SolutionsIdContratarRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/builder/': typeof AuthenticatedBuilderIndexRoute
  '/cursos/': typeof AuthenticatedCursosIndexRoute
  '/implementador/': typeof AuthenticatedImplementadorIndexRoute
  '/mentoria/': typeof AuthenticatedMentoriaIndexRoute
  '/solutions/': typeof AuthenticatedSolutionsIndexRoute
  '/admin/cursos/$courseId': typeof AuthenticatedAdminCursosCourseIdRoute
  '/implementador/proyecto/$projectId': typeof AuthenticatedImplementadorProyectoProjectIdRoute
  '/admin/cursos/': typeof AuthenticatedAdminCursosIndexRoute
  '/cursos/$courseId/leccion/$lessonId': typeof AuthenticatedCursosCourseIdLeccionLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/contratar-experto': typeof AuthenticatedContratarExpertoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mi-progreso': typeof AuthenticatedMiProgresoRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/contratar/confirmacion': typeof ContratarConfirmacionRoute
  '/cursos/$courseId': typeof AuthenticatedCursosCourseIdRouteWithChildren
  '/solutions/$id': typeof AuthenticatedSolutionsIdRoute
  '/solutions/$slug': typeof AuthenticatedSolutionsSlugRoute
  '/solutions/$id/contratar': typeof SolutionsIdContratarRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/builder': typeof AuthenticatedBuilderIndexRoute
  '/cursos': typeof AuthenticatedCursosIndexRoute
  '/implementador': typeof AuthenticatedImplementadorIndexRoute
  '/mentoria': typeof AuthenticatedMentoriaIndexRoute
  '/solutions': typeof AuthenticatedSolutionsIndexRoute
  '/admin/cursos/$courseId': typeof AuthenticatedAdminCursosCourseIdRoute
  '/implementador/proyecto/$projectId': typeof AuthenticatedImplementadorProyectoProjectIdRoute
  '/admin/cursos': typeof AuthenticatedAdminCursosIndexRoute
  '/cursos/$courseId/leccion/$lessonId': typeof AuthenticatedCursosCourseIdLeccionLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/contratar-experto': typeof AuthenticatedContratarExpertoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/mi-progreso': typeof AuthenticatedMiProgresoRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/contratar/confirmacion': typeof ContratarConfirmacionRoute
  '/_authenticated/cursos/$courseId': typeof AuthenticatedCursosCourseIdRouteWithChildren
  '/_authenticated/solutions/$id': typeof AuthenticatedSolutionsIdRoute
  '/_authenticated/solutions/$slug': typeof AuthenticatedSolutionsSlugRoute
  '/solutions/$id/contratar': typeof SolutionsIdContratarRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/builder/': typeof AuthenticatedBuilderIndexRoute
  '/_authenticated/cursos/': typeof AuthenticatedCursosIndexRoute
  '/_authenticated/implementador/': typeof AuthenticatedImplementadorIndexRoute
  '/_authenticated/mentoria/': typeof AuthenticatedMentoriaIndexRoute
  '/_authenticated/solutions/': typeof AuthenticatedSolutionsIndexRoute
  '/_authenticated/admin/cursos/$courseId': typeof AuthenticatedAdminCursosCourseIdRoute
  '/_authenticated/implementador/proyecto/$projectId': typeof AuthenticatedImplementadorProyectoProjectIdRoute
  '/_authenticated/admin/cursos/': typeof AuthenticatedAdminCursosIndexRoute
  '/_authenticated/cursos/$courseId/leccion/$lessonId': typeof AuthenticatedCursosCourseIdLeccionLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contratar-experto'
    | '/dashboard'
    | '/mi-progreso'
    | '/projects'
    | '/settings'
    | '/contratar/confirmacion'
    | '/cursos/$courseId'
    | '/solutions/$id'
    | '/solutions/$slug'
    | '/solutions/$id/contratar'
    | '/admin/'
    | '/builder/'
    | '/cursos/'
    | '/implementador/'
    | '/mentoria/'
    | '/solutions/'
    | '/admin/cursos/$courseId'
    | '/implementador/proyecto/$projectId'
    | '/admin/cursos/'
    | '/cursos/$courseId/leccion/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/contratar-experto'
    | '/dashboard'
    | '/mi-progreso'
    | '/projects'
    | '/settings'
    | '/contratar/confirmacion'
    | '/cursos/$courseId'
    | '/solutions/$id'
    | '/solutions/$slug'
    | '/solutions/$id/contratar'
    | '/admin'
    | '/builder'
    | '/cursos'
    | '/implementador'
    | '/mentoria'
    | '/solutions'
    | '/admin/cursos/$courseId'
    | '/implementador/proyecto/$projectId'
    | '/admin/cursos'
    | '/cursos/$courseId/leccion/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/contratar-experto'
    | '/_authenticated/dashboard'
    | '/_authenticated/mi-progreso'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/contratar/confirmacion'
    | '/_authenticated/cursos/$courseId'
    | '/_authenticated/solutions/$id'
    | '/_authenticated/solutions/$slug'
    | '/solutions/$id/contratar'
    | '/_authenticated/admin/'
    | '/_authenticated/builder/'
    | '/_authenticated/cursos/'
    | '/_authenticated/implementador/'
    | '/_authenticated/mentoria/'
    | '/_authenticated/solutions/'
    | '/_authenticated/admin/cursos/$courseId'
    | '/_authenticated/implementador/proyecto/$projectId'
    | '/_authenticated/admin/cursos/'
    | '/_authenticated/cursos/$courseId/leccion/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ContratarConfirmacionRoute: typeof ContratarConfirmacionRoute
  SolutionsIdContratarRoute: typeof SolutionsIdContratarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratar/confirmacion': {
      id: '/contratar/confirmacion'
      path: '/contratar/confirmacion'
      fullPath: '/contratar/confirmacion'
      preLoaderRoute: typeof ContratarConfirmacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mi-progreso': {
      id: '/_authenticated/mi-progreso'
      path: '/mi-progreso'
      fullPath: '/mi-progreso'
      preLoaderRoute: typeof AuthenticatedMiProgresoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratar-experto': {
      id: '/_authenticated/contratar-experto'
      path: '/contratar-experto'
      fullPath: '/contratar-experto'
      preLoaderRoute: typeof AuthenticatedContratarExpertoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/solutions/': {
      id: '/_authenticated/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof AuthenticatedSolutionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mentoria/': {
      id: '/_authenticated/mentoria/'
      path: '/mentoria'
      fullPath: '/mentoria/'
      preLoaderRoute: typeof AuthenticatedMentoriaIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/implementador/': {
      id: '/_authenticated/implementador/'
      path: '/implementador'
      fullPath: '/implementador/'
      preLoaderRoute: typeof AuthenticatedImplementadorIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cursos/': {
      id: '/_authenticated/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof AuthenticatedCursosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/builder/': {
      id: '/_authenticated/builder/'
      path: '/builder'
      fullPath: '/builder/'
      preLoaderRoute: typeof AuthenticatedBuilderIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/solutions/$id/contratar': {
      id: '/solutions/$id/contratar'
      path: '/solutions/$id/contratar'
      fullPath: '/solutions/$id/contratar'
      preLoaderRoute: typeof SolutionsIdContratarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/solutions/$slug': {
      id: '/_authenticated/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof AuthenticatedSolutionsSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/solutions/$id': {
      id: '/_authenticated/solutions/$id'
      path: '/solutions/$id'
      fullPath: '/solutions/$id'
      preLoaderRoute: typeof AuthenticatedSolutionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cursos/$courseId': {
      id: '/_authenticated/cursos/$courseId'
      path: '/cursos/$courseId'
      fullPath: '/cursos/$courseId'
      preLoaderRoute: typeof AuthenticatedCursosCourseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cursos/': {
      id: '/_authenticated/admin/cursos/'
      path: '/admin/cursos'
      fullPath: '/admin/cursos/'
      preLoaderRoute: typeof AuthenticatedAdminCursosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/implementador/proyecto/$projectId': {
      id: '/_authenticated/implementador/proyecto/$projectId'
      path: '/implementador/proyecto/$projectId'
      fullPath: '/implementador/proyecto/$projectId'
      preLoaderRoute: typeof AuthenticatedImplementadorProyectoProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/cursos/$courseId': {
      id: '/_authenticated/admin/cursos/$courseId'
      path: '/admin/cursos/$courseId'
      fullPath: '/admin/cursos/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminCursosCourseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cursos/$courseId/leccion/$lessonId': {
      id: '/_authenticated/cursos/$courseId/leccion/$lessonId'
      path: '/leccion/$lessonId'
      fullPath: '/cursos/$courseId/leccion/$lessonId'
      preLoaderRoute: typeof AuthenticatedCursosCourseIdLeccionLessonIdRouteImport
      parentRoute: typeof AuthenticatedCursosCourseIdRoute
    }
  }
}

interface AuthenticatedCursosCourseIdRouteChildren {
  AuthenticatedCursosCourseIdLeccionLessonIdRoute: typeof AuthenticatedCursosCourseIdLeccionLessonIdRoute
}

const AuthenticatedCursosCourseIdRouteChildren: AuthenticatedCursosCourseIdRouteChildren =
  {
    AuthenticatedCursosCourseIdLeccionLessonIdRoute:
      AuthenticatedCursosCourseIdLeccionLessonIdRoute,
  }

const AuthenticatedCursosCourseIdRouteWithChildren =
  AuthenticatedCursosCourseIdRoute._addFileChildren(
    AuthenticatedCursosCourseIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedContratarExpertoRoute: typeof AuthenticatedContratarExpertoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMiProgresoRoute: typeof AuthenticatedMiProgresoRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedCursosCourseIdRoute: typeof AuthenticatedCursosCourseIdRouteWithChildren
  AuthenticatedSolutionsIdRoute: typeof AuthenticatedSolutionsIdRoute
  AuthenticatedSolutionsSlugRoute: typeof AuthenticatedSolutionsSlugRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedBuilderIndexRoute: typeof AuthenticatedBuilderIndexRoute
  AuthenticatedCursosIndexRoute: typeof AuthenticatedCursosIndexRoute
  AuthenticatedImplementadorIndexRoute: typeof AuthenticatedImplementadorIndexRoute
  AuthenticatedMentoriaIndexRoute: typeof AuthenticatedMentoriaIndexRoute
  AuthenticatedSolutionsIndexRoute: typeof AuthenticatedSolutionsIndexRoute
  AuthenticatedAdminCursosCourseIdRoute: typeof AuthenticatedAdminCursosCourseIdRoute
  AuthenticatedImplementadorProyectoProjectIdRoute: typeof AuthenticatedImplementadorProyectoProjectIdRoute
  AuthenticatedAdminCursosIndexRoute: typeof AuthenticatedAdminCursosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContratarExpertoRoute: AuthenticatedContratarExpertoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMiProgresoRoute: AuthenticatedMiProgresoRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedCursosCourseIdRoute:
    AuthenticatedCursosCourseIdRouteWithChildren,
  AuthenticatedSolutionsIdRoute: AuthenticatedSolutionsIdRoute,
  AuthenticatedSolutionsSlugRoute: AuthenticatedSolutionsSlugRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedBuilderIndexRoute: AuthenticatedBuilderIndexRoute,
  AuthenticatedCursosIndexRoute: AuthenticatedCursosIndexRoute,
  AuthenticatedImplementadorIndexRoute: AuthenticatedImplementadorIndexRoute,
  AuthenticatedMentoriaIndexRoute: AuthenticatedMentoriaIndexRoute,
  AuthenticatedSolutionsIndexRoute: AuthenticatedSolutionsIndexRoute,
  AuthenticatedAdminCursosCourseIdRoute: AuthenticatedAdminCursosCourseIdRoute,
  AuthenticatedImplementadorProyectoProjectIdRoute:
    AuthenticatedImplementadorProyectoProjectIdRoute,
  AuthenticatedAdminCursosIndexRoute: AuthenticatedAdminCursosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ContratarConfirmacionRoute: ContratarConfirmacionRoute,
  SolutionsIdContratarRoute: SolutionsIdContratarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
