/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContratarConfirmacionRouteImport } from './routes/contratar.confirmacion'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSolutionsIndexRouteImport } from './routes/_authenticated/solutions.index'
import { Route as AuthenticatedCursosIndexRouteImport } from './routes/_authenticated/cursos.index'
import { Route as SolutionsIdContratarRouteImport } from './routes/solutions.$id.contratar'
import { Route as AuthenticatedSolutionsSlugRouteImport } from './routes/_authenticated/solutions.$slug'
import { Route as AuthenticatedSolutionsIdRouteImport } from './routes/_authenticated/solutions.$id'
import { Route as AuthenticatedBuilderSolutionIdRouteImport } from './routes/_authenticated/builder.$solutionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratarConfirmacionRoute = ContratarConfirmacionRouteImport.update({
  id: '/contratar/confirmacion',
  path: '/contratar/confirmacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSolutionsIndexRoute =
  AuthenticatedSolutionsIndexRouteImport.update({
    id: '/solutions/',
    path: '/solutions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCursosIndexRoute =
  AuthenticatedCursosIndexRouteImport.update({
    id: '/cursos/',
    path: '/cursos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const SolutionsIdContratarRoute = SolutionsIdContratarRouteImport.update({
  id: '/solutions/$id/contratar',
  path: '/solutions/$id/contratar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSolutionsSlugRoute =
  AuthenticatedSolutionsSlugRouteImport.update({
    id: '/solutions/$slug',
    path: '/solutions/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSolutionsIdRoute =
  AuthenticatedSolutionsIdRouteImport.update({
    id: '/solutions/$id',
    path: '/solutions/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBuilderSolutionIdRoute =
  AuthenticatedBuilderSolutionIdRouteImport.update({
    id: '/builder/$solutionId',
    path: '/builder/$solutionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/contratar/confirmacion': typeof ContratarConfirmacionRoute
  '/builder/$solutionId': typeof AuthenticatedBuilderSolutionIdRoute
  '/solutions/$id': typeof AuthenticatedSolutionsIdRoute
  '/solutions/$slug': typeof AuthenticatedSolutionsSlugRoute
  '/solutions/$id/contratar': typeof SolutionsIdContratarRoute
  '/cursos/': typeof AuthenticatedCursosIndexRoute
  '/solutions/': typeof AuthenticatedSolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/contratar/confirmacion': typeof ContratarConfirmacionRoute
  '/builder/$solutionId': typeof AuthenticatedBuilderSolutionIdRoute
  '/solutions/$id': typeof AuthenticatedSolutionsIdRoute
  '/solutions/$slug': typeof AuthenticatedSolutionsSlugRoute
  '/solutions/$id/contratar': typeof SolutionsIdContratarRoute
  '/cursos': typeof AuthenticatedCursosIndexRoute
  '/solutions': typeof AuthenticatedSolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/contratar/confirmacion': typeof ContratarConfirmacionRoute
  '/_authenticated/builder/$solutionId': typeof AuthenticatedBuilderSolutionIdRoute
  '/_authenticated/solutions/$id': typeof AuthenticatedSolutionsIdRoute
  '/_authenticated/solutions/$slug': typeof AuthenticatedSolutionsSlugRoute
  '/solutions/$id/contratar': typeof SolutionsIdContratarRoute
  '/_authenticated/cursos/': typeof AuthenticatedCursosIndexRoute
  '/_authenticated/solutions/': typeof AuthenticatedSolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/projects'
    | '/settings'
    | '/contratar/confirmacion'
    | '/builder/$solutionId'
    | '/solutions/$id'
    | '/solutions/$slug'
    | '/solutions/$id/contratar'
    | '/cursos/'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/projects'
    | '/settings'
    | '/contratar/confirmacion'
    | '/builder/$solutionId'
    | '/solutions/$id'
    | '/solutions/$slug'
    | '/solutions/$id/contratar'
    | '/cursos'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/contratar/confirmacion'
    | '/_authenticated/builder/$solutionId'
    | '/_authenticated/solutions/$id'
    | '/_authenticated/solutions/$slug'
    | '/solutions/$id/contratar'
    | '/_authenticated/cursos/'
    | '/_authenticated/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ContratarConfirmacionRoute: typeof ContratarConfirmacionRoute
  SolutionsIdContratarRoute: typeof SolutionsIdContratarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratar/confirmacion': {
      id: '/contratar/confirmacion'
      path: '/contratar/confirmacion'
      fullPath: '/contratar/confirmacion'
      preLoaderRoute: typeof ContratarConfirmacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/solutions/': {
      id: '/_authenticated/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof AuthenticatedSolutionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cursos/': {
      id: '/_authenticated/cursos/'
      path: '/cursos'
      fullPath: '/cursos/'
      preLoaderRoute: typeof AuthenticatedCursosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/solutions/$id/contratar': {
      id: '/solutions/$id/contratar'
      path: '/solutions/$id/contratar'
      fullPath: '/solutions/$id/contratar'
      preLoaderRoute: typeof SolutionsIdContratarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/solutions/$slug': {
      id: '/_authenticated/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof AuthenticatedSolutionsSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/solutions/$id': {
      id: '/_authenticated/solutions/$id'
      path: '/solutions/$id'
      fullPath: '/solutions/$id'
      preLoaderRoute: typeof AuthenticatedSolutionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/builder/$solutionId': {
      id: '/_authenticated/builder/$solutionId'
      path: '/builder/$solutionId'
      fullPath: '/builder/$solutionId'
      preLoaderRoute: typeof AuthenticatedBuilderSolutionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedBuilderSolutionIdRoute: typeof AuthenticatedBuilderSolutionIdRoute
  AuthenticatedSolutionsIdRoute: typeof AuthenticatedSolutionsIdRoute
  AuthenticatedSolutionsSlugRoute: typeof AuthenticatedSolutionsSlugRoute
  AuthenticatedCursosIndexRoute: typeof AuthenticatedCursosIndexRoute
  AuthenticatedSolutionsIndexRoute: typeof AuthenticatedSolutionsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedBuilderSolutionIdRoute: AuthenticatedBuilderSolutionIdRoute,
  AuthenticatedSolutionsIdRoute: AuthenticatedSolutionsIdRoute,
  AuthenticatedSolutionsSlugRoute: AuthenticatedSolutionsSlugRoute,
  AuthenticatedCursosIndexRoute: AuthenticatedCursosIndexRoute,
  AuthenticatedSolutionsIndexRoute: AuthenticatedSolutionsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ContratarConfirmacionRoute: ContratarConfirmacionRoute,
  SolutionsIdContratarRoute: SolutionsIdContratarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
