ALTER TABLE public.solutions ADD COLUMN IF NOT EXISTS prompt_template text;
ALTER TABLE public.solutions ADD COLUMN IF NOT EXISTS features text[] NOT NULL DEFAULT '{}';
ALTER TABLE public.solutions ADD COLUMN IF NOT EXISTS integrations text[] NOT NULL DEFAULT '{}';

DELETE FROM public.saved_solutions;
DELETE FROM public.solutions;

INSERT INTO public.solutions
(slug, title, short_description, long_description, category, difficulty, tools_required, estimated_time, roi_estimate, icon_name, is_featured, prompt_template, features, integrations)
VALUES
('sdr-automatizado-whatsapp','SDR Automatizado por WhatsApp',
 'Agente de ventas inteligente 24/7 por WhatsApp. Atiende, califica leads, agenda reuniones y escala al humano cuando el lead está listo.',
 'Agente de ventas inteligente que trabaja 24/7 por WhatsApp. Atiende consultas entrantes, califica leads con preguntas personalizadas según tu industria, agenda reuniones automáticamente en tu calendario y escala al vendedor humano cuando el lead está listo para cerrar. Se conecta con tu CRM y genera reportes diarios de conversiones.',
 'ventas','intermedio',
 ARRAY['n8n','WhatsApp Business API','OpenAI GPT-4','Google Calendar','CRM'],
 '8-12 horas','3-5x en 60 días','MessageCircle',true,
 E'Construye un SDR automatizado para WhatsApp para [CONTEXTO].\n\n- Conectarse a WhatsApp Business API oficial de Meta\n- Usar OpenAI GPT-4 para respuestas personalizadas\n- Calificar leads: presupuesto, urgencia, decisor, necesidad\n- Integrar Google Calendar para agendar\n- Escalar a humano cuando lead score > 70/100\n- Reporte diario al equipo\n\nStack: n8n + Supabase + OpenAI.',
 ARRAY['Calificación automática de leads','Agendamiento de reuniones','Escalado inteligente a humano','Reportes diarios de conversión','Integración con CRM','Memoria de conversación por contacto'],
 ARRAY['WhatsApp Business API','Google Calendar','n8n','OpenAI','Supabase']),
('campanas-whatsapp-meta','Campañas WhatsApp con API Oficial Meta',
 'Envío masivo profesional con API oficial de WhatsApp. Templates aprobados, segmentación, programación y métricas en tiempo real.',
 'Sistema profesional de envío masivo de mensajes usando la API oficial de WhatsApp Business de Meta. Gestiona templates aprobados, segmenta audiencias por comportamiento y etiquetas, programa envíos y obtén métricas detalladas de entrega, lectura y respuesta en tiempo real. Cumple con todas las políticas de Meta para evitar bloqueos.',
 'marketing','intermedio',
 ARRAY['WhatsApp Business API','Meta','n8n','Supabase'],
 '6-8 horas','2-4x en alcance','Megaphone',true,
 E'Construye una plataforma de envío masivo WhatsApp con API oficial de Meta para [CONTEXTO].\n\n- Panel de templates con variables dinámicas\n- Importación de contactos por CSV con etiquetas\n- Programador con rate limiting según Meta\n- Dashboard: enviados, entregados, leídos, respondidos\n- Opt-out automático (STOP)\n- Exportación a Excel\n\nStack: Lovable + Supabase + n8n.',
 ARRAY['Templates aprobados por Meta','Segmentación de audiencias','Programación de envíos','Métricas en tiempo real','Gestión de opt-out','Exportación de reportes'],
 ARRAY['WhatsApp Business API','Meta Business','n8n','Supabase']),
('crm-inteligente-ia','CRM Inteligente con IA',
 'CRM con pipeline Kanban, scoring automático de leads, resúmenes con IA y próximas acciones sugeridas.',
 'CRM completo diseñado para equipos de ventas de empresas medianas. Pipeline visual tipo Kanban con drag & drop, scoring automático de leads basado en comportamiento, resúmenes de cada conversación generados por IA, próximas acciones sugeridas automáticamente y alertas de seguimiento. Construido con Lovable y Supabase — 100% personalizable.',
 'ventas','intermedio',
 ARRAY['Lovable','Supabase','OpenAI GPT-4','n8n'],
 '12-16 horas','+30% conversión','Briefcase',true,
 E'Construye un CRM inteligente con IA para [CONTEXTO].\n\n- Pipeline Kanban: Nuevo → Contactado → Calificado → Propuesta → Negociación → Cerrado\n- Drag & drop con persistencia en DB\n- Ficha completa de lead\n- Score automático 0-100\n- Botón "Resumir con IA" y "Próxima acción"\n- Filtros y dashboard\n- Alertas de inactividad\n\nStack: Lovable + Supabase + OpenAI GPT-4.',
 ARRAY['Pipeline Kanban con drag & drop','Score automático de leads','Resumen de conversaciones con IA','Próximas acciones sugeridas','Alertas de seguimiento','Dashboard de métricas de ventas'],
 ARRAY['Lovable','Supabase','OpenAI GPT-4','n8n']),
('analisis-seo-ia','Análisis SEO Completo con IA',
 'Auditoría SEO automatizada con keywords, competencia, errores técnicos y plan de acción mensual generado por IA.',
 'Auditoría SEO automatizada que analiza tu sitio web en profundidad: palabras clave con mayor potencial, análisis de la competencia, errores técnicos, oportunidades de contenido y un plan de acción mensual priorizado. Todo generado automáticamente con IA y presentado en un reporte claro y accionable para tu equipo.',
 'marketing','principiante',
 ARRAY['OpenAI GPT-4','n8n','Google Search Console API','Lovable','Supabase'],
 '4-6 horas','+40% tráfico orgánico','Search',true,
 E'Construye una herramienta de análisis SEO automatizado con IA para [CONTEXTO].\n\n- Conexión con Google Search Console API\n- Análisis de keywords: volumen, posición, CTR\n- Detección de errores técnicos\n- Análisis de 3 competidores\n- Plan de contenidos mensual con OpenAI\n- Dashboard de métricas\n- Exportar reporte PDF priorizado\n\nStack: Lovable + n8n + Supabase + OpenAI.',
 ARRAY['Conexión Google Search Console','Análisis de competencia','Detección de errores técnicos','Plan de contenidos con IA','Reporte exportable PDF','Tracking de posiciones en el tiempo'],
 ARRAY['Google Search Console API','OpenAI GPT-4','n8n','Lovable','Supabase']),
('chatbot-omnicanal','Chatbot de Atención Omnicanal',
 'Chatbot que atiende WhatsApp, email e Instagram con base de conocimiento unificada y escalado a humano.',
 'Chatbot inteligente que atiende a tus clientes simultáneamente en WhatsApp, email e Instagram con la misma base de conocimiento. Responde consultas frecuentes, procesa pedidos simples, abre tickets de soporte y escala automáticamente a un agente humano cuando la situación lo requiere. Incluye panel de supervisión en tiempo real y métricas de satisfacción.',
 'atencion','intermedio',
 ARRAY['n8n','WhatsApp Business API','OpenAI GPT-4','Supabase','Gmail API'],
 '10-14 horas','-60% tickets manuales','Headphones',true,
 E'Construye un chatbot omnicanal de atención al cliente para [CONTEXTO].\n\nCanales: WhatsApp + Gmail + Instagram DM\n\n- Base de conocimiento editable\n- Motor OpenAI con respuesta natural\n- Detección de intención\n- Escalado a humano automático\n- Panel de supervisión + CSAT\n- Sistema de tickets\n- Encuesta automática post-atención\n\nStack: n8n + Supabase + OpenAI + Lovable.',
 ARRAY['Atención en WhatsApp + Email + Instagram','Base de conocimiento personalizable','Escalado automático a humano','Panel de supervisión en tiempo real','Sistema de tickets integrado','Métricas de satisfacción (CSAT)'],
 ARRAY['WhatsApp Business API','Gmail API','Instagram API','OpenAI GPT-4','n8n','Supabase']),
('agente-cobranza-ia','Agente de Cobranza con IA',
 'Automatiza el seguimiento de pagos vencidos con mensajes personalizados según el perfil de cada deudor.',
 'Sistema inteligente que automatiza el seguimiento de pagos vencidos con mensajes personalizados según el perfil de cada deudor — su historial de pagos, monto adeudado y días de mora. Genera propuestas de acuerdo de pago, escala los casos críticos al equipo humano y produce reportes de recuperación diarios con tasas de éxito por segmento.',
 'finanzas','intermedio',
 ARRAY['n8n','WhatsApp Business API','OpenAI GPT-4','Supabase'],
 '6-8 horas','+25% recuperación','Wallet',true,
 E'Construye un agente de cobranza automatizado con IA para [CONTEXTO].\n\n- Importar cartera por CSV\n- Segmentar: 1-30 / 31-60 / 60+ días\n- Mensajes personalizados con OpenAI\n- Recordatorios WhatsApp en horarios configurables\n- Plan de pagos automático\n- Escalado a gestor humano\n- Dashboard de recuperación\n- Reporte diario\n\nStack: n8n + WhatsApp Business API + OpenAI + Supabase.',
 ARRAY['Segmentación por nivel de mora','Mensajes personalizados por perfil','Propuesta automática de plan de pagos','Escalado a gestor humano','Dashboard de recuperación','Reporte diario automático'],
 ARRAY['WhatsApp Business API','OpenAI GPT-4','n8n','Supabase']),
('portal-del-cliente','Portal del Cliente',
 'Portal self-service para consultar pedidos, descargar facturas, abrir tickets y acceder al historial.',
 'Portal self-service profesional donde tus clientes pueden hacer todo sin llamar a tu equipo: consultar el estado de sus pedidos en tiempo real, descargar facturas y documentos, abrir y hacer seguimiento de tickets de soporte, acceder a su historial completo y comunicarse directamente con el área correspondiente. Reduce el 60% de las consultas entrantes al equipo de soporte.',
 'atencion','intermedio',
 ARRAY['Lovable','Supabase','OpenAI GPT-4'],
 '10-14 horas','-60% consultas entrantes','LayoutDashboard',true,
 E'Construye un portal self-service para clientes para [CONTEXTO].\n\n1. Dashboard del cliente\n2. Mis Pedidos con tracking\n3. Documentos descargables (PDF)\n4. Soporte: tickets con adjuntos\n5. Mi Cuenta\n6. Chat IA con base de conocimiento\n\nAuth con RLS Supabase. Diseño con branding de [CONTEXTO], responsive.\n\nStack: Lovable + Supabase + OpenAI.',
 ARRAY['Seguimiento de pedidos en tiempo real','Descarga de facturas y documentos','Sistema de tickets de soporte','Chat IA para consultas frecuentes','Historial completo del cliente','Notificaciones automáticas'],
 ARRAY['Lovable','Supabase','OpenAI GPT-4']),
('gestion-rrhh-ia','Gestión de RRHH con IA',
 'Plataforma de RRHH con screening de CVs, onboarding digital, evaluaciones 360° y chatbot interno.',
 'Plataforma completa de Recursos Humanos potenciada con IA: screening automático de CVs con scoring por fit cultural y técnico, flujo de onboarding digital para nuevos empleados, evaluaciones de desempeño 360° con análisis de IA, chatbot interno que responde dudas sobre beneficios y políticas, y dashboard de indicadores de clima organizacional.',
 'rrhh','intermedio',
 ARRAY['Lovable','Supabase','OpenAI GPT-4','n8n'],
 '12-16 horas','-50% tiempo de hire','Users',true,
 E'Construye una plataforma de RRHH con IA para [CONTEXTO].\n\n1. RECLUTAMIENTO: postulación pública + análisis CV con OpenAI + ranking + Kanban\n2. ONBOARDING: checklist digital y tareas automáticas\n3. EVALUACIONES 360° con análisis IA y PDI\n4. CHATBOT INTERNO sobre políticas\n5. DASHBOARD HR\n\nStack: Lovable + Supabase (roles admin/empleado/candidato) + OpenAI + n8n.',
 ARRAY['Screening automático de CVs con score IA','Onboarding digital paso a paso','Evaluaciones de desempeño 360°','Chatbot de consultas internas','Dashboard de indicadores HR','Gestión de documentos y firmas'],
 ARRAY['Lovable','Supabase','OpenAI GPT-4','n8n']);