
INSERT INTO public.solutions (slug, title, category, short_description, long_description, difficulty, estimated_time, roi_estimate, tools_required, icon_name, is_featured) VALUES
-- VENTAS
('sdr-automatizado-whatsapp','SDR Automatizado por WhatsApp','ventas','Califica leads 24/7, agenda reuniones y se integra con tu CRM.','Un agente de IA que responde tus WhatsApps fuera de horario, califica al lead haciendo preguntas clave y agenda reuniones automáticamente en tu Calendly. Integra con tu CRM para crear el contacto y registrar toda la conversación.','intermedio','1 día','+40% reuniones agendadas',ARRAY['WhatsApp Business API','OpenAI','Calendly'],'MessageSquare',true),
('analisis-llamadas-ventas','Análisis de Llamadas de Ventas con IA','ventas','Transcribe y analiza calls, detecta objeciones recurrentes.','Cada llamada de ventas se transcribe automáticamente, la IA detecta objeciones recurrentes, identifica patrones de cierre y genera coaching personalizado para cada vendedor.','principiante','2 horas','+25% close rate',ARRAY['Fireflies','OpenAI'],'PhoneCall',false),
('generador-propuestas','Generador de Propuestas Comerciales','ventas','Crea propuestas personalizadas desde la información del lead.','A partir de las notas de descubrimiento y datos del lead, la IA genera una propuesta comercial personalizada con alcance, precios y casos similares en menos de 60 segundos.','principiante','2 horas','−60% tiempo de propuesta',ARRAY['Notion','OpenAI'],'FileText',false),
('lead-scoring-predictivo','Lead Scoring Predictivo','ventas','Puntúa leads según probabilidad de cierre.','Un modelo de IA analiza el comportamiento del lead, datos firmográficos e interacciones para asignarle un score predictivo. Tu equipo comercial enfoca tiempo donde hay más probabilidad de cierre.','avanzado','1 día','+35% eficiencia comercial',ARRAY['HubSpot','OpenAI'],'TrendingUp',false),
('followup-post-reunion','Follow-up Automático Post-Reunión','ventas','Envía resumen + próximos pasos automáticamente.','Al terminar la reunión, la IA genera un resumen accionable y un email de follow-up con próximos pasos, que se envía automáticamente al prospecto.','principiante','1 hora','+50% tasa de respuesta',ARRAY['Gmail','OpenAI','Zapier'],'Mail',false),
('cold-outreach-personalizado','Asistente de Cold Outreach Hiper-Personalizado','ventas','Investiga prospecto y genera primer mensaje.','La IA investiga al prospecto (LinkedIn, web, noticias) y redacta un primer mensaje hiper-personalizado que no parece automatizado. Triplica respuestas vs templates genéricos.','intermedio','3 horas','+3x respuestas',ARRAY['Apollo','OpenAI'],'Target',true),

-- MARKETING
('generador-copy-ads','Generador de Copy para Anuncios (Meta/Google)','marketing','Crea 10 variantes A/B testeables.','A partir de un brief, la IA genera 10 variantes de copy listas para A/B testear en Meta Ads y Google Ads, optimizadas para CTR y conversión.','principiante','2 horas','−80% tiempo creación',ARRAY['OpenAI'],'Megaphone',true),
('analisis-competencia','Análisis de Competencia Automatizado','marketing','Monitorea anuncios y contenido de competidores.','La IA monitorea semanalmente los anuncios, blogs y redes de tus competidores. Te entrega un reporte ejecutivo con cambios de estrategia, nuevos ángulos y oportunidades.','intermedio','4 horas','insights semanales sin esfuerzo',ARRAY['SimilarWeb','OpenAI'],'Eye',false),
('pipeline-contenido','Pipeline de Contenido (Blog → LinkedIn → IG)','marketing','Un brief, todos los formatos.','Con un solo brief, la IA crea el artículo de blog, lo adapta a LinkedIn, genera 5 posts de Instagram y un newsletter. Multiplicas tu output 10x sin perder calidad.','principiante','3 horas','10x output de contenido',ARRAY['OpenAI','Buffer'],'Layers',true),
('editor-seo','Editor SEO con IA','marketing','Optimiza artículos para keywords objetivo.','La IA analiza tu artículo, lo optimiza para tu keyword objetivo, sugiere headings, internal links y mejoras estructurales sin perder tu tono.','intermedio','3 horas','+60% tráfico orgánico',ARRAY['OpenAI','Ahrefs'],'Search',false),
('email-newsletter','Generador de Email Newsletters','marketing','Curate + redacta newsletter semanal.','La IA recoge contenido relevante de tu industria, curate los mejores artículos y redacta un newsletter semanal con tu tono editorial.','principiante','2 horas','4h ahorradas/semana',ARRAY['OpenAI','Beehiiv'],'Newspaper',false),
('sentimiento-redes','Análisis de Sentimiento en Redes','marketing','Detecta menciones positivas/negativas y alerta.','La IA monitorea menciones de tu marca en redes sociales, clasifica el sentimiento y te alerta en Slack ante crisis o oportunidades de respuesta.','avanzado','1 día','respuesta a crisis en minutos',ARRAY['Brand24','OpenAI'],'Activity',false),

-- ATENCIÓN
('chatbot-whatsapp-multinivel','Chatbot WhatsApp Multinivel con IA','atencion','Atiende, califica y deriva.','Un chatbot multinivel que entiende lenguaje natural, atiende consultas frecuentes, califica leads y deriva a un humano cuando es necesario. Reduce 70% los tickets manuales.','intermedio','1 día','−70% tickets humanos',ARRAY['WhatsApp API','OpenAI'],'MessagesSquare',true),
('triage-tickets','Triage Automático de Tickets','atencion','Clasifica y prioriza tickets entrantes.','La IA lee cada ticket entrante, lo clasifica por categoría y urgencia, lo asigna al agente correcto y prioriza la cola automáticamente.','intermedio','3 horas','−50% tiempo resolución',ARRAY['Zendesk','OpenAI'],'Inbox',false),
('faq-dinamico','FAQ Dinámico desde Historial','atencion','Auto-genera FAQs desde tickets resueltos.','La IA analiza tus tickets resueltos del último mes, identifica las preguntas más frecuentes y genera un FAQ dinámico que reduce 40% los tickets repetitivos.','principiante','2 horas','−40% tickets repetitivos',ARRAY['Intercom','OpenAI'],'HelpCircle',false),
('detector-churn','Detector de Clientes en Riesgo de Churn','atencion','Analiza señales y alerta CSM.','La IA monitorea uso del producto, sentimiento en tickets y engagement. Cuando detecta señales de churn, alerta al CSM con un playbook de retención personalizado.','avanzado','1 día','+20% retención',ARRAY['HubSpot','OpenAI'],'AlertTriangle',true),
('respuestas-sugeridas','Respuestas Sugeridas para Agentes','atencion','Asistente in-chat para humanos.','Mientras tu agente humano responde un ticket, la IA sugiere respuestas, busca casos similares resueltos y le ahorra 30% del tiempo por ticket.','intermedio','3 horas','−30% tiempo por ticket',ARRAY['Crisp','OpenAI'],'Sparkles',false),
('encuestas-nps','Encuestas NPS Inteligentes','atencion','Analiza respuestas abiertas automáticamente.','La IA procesa todas las respuestas abiertas de tus encuestas NPS, las clasifica por tema y te entrega insights cualitativos en horas, no semanas.','principiante','2 horas','insights cualitativos en horas',ARRAY['Typeform','OpenAI'],'BarChart3',false),

-- FINANZAS
('conciliacion-bancaria','Conciliación Bancaria con IA','finanzas','Cruza extractos con facturas.','La IA lee tus extractos bancarios y los cruza automáticamente con facturas emitidas y pagadas. Reduce 80% el tiempo de conciliación mensual.','intermedio','4 horas','−80% tiempo conciliación',ARRAY['Belvo','OpenAI'],'CheckCircle2',false),
('cashflow-predictivo','Análisis de Cash Flow Predictivo','finanzas','Proyecta caja a 90 días.','Combina tus ingresos recurrentes, pagos pendientes y patrones históricos para proyectar tu caja a 90 días con escenarios optimista, base y pesimista.','avanzado','1 día','cero sorpresas de caja',ARRAY['Google Sheets','OpenAI'],'LineChart',true),
('categorizacion-gastos','Categorización Automática de Gastos','finanzas','Clasifica transacciones por categoría contable.','La IA categoriza cada gasto según tu plan de cuentas, sugiere centros de costo y prepara la información lista para tu contador.','principiante','2 horas','−90% tiempo contable',ARRAY['OpenAI','Google Sheets'],'Tags',false),
('reportes-mensuales','Generador de Reportes Mensuales','finanzas','P&L narrado en lenguaje natural para socios.','La IA toma tu P&L y genera un reporte ejecutivo narrado en lenguaje natural, listo para enviar a socios o inversores.','principiante','2 horas','reportes en minutos no días',ARRAY['OpenAI'],'FileBarChart',false),
('anomalias-gastos','Detector de Anomalías en Gastos','finanzas','Alerta sobre gastos inusuales.','La IA aprende tus patrones de gasto y te alerta en Slack cuando detecta transacciones inusuales: posibles fraudes, errores o gastos fuera de presupuesto.','intermedio','3 horas','prevención de fraude',ARRAY['OpenAI','Slack'],'ShieldAlert',false),
('cobranza-inteligente','Asistente de Cobranza Inteligente','finanzas','Mensajes personalizados según perfil de moroso.','La IA segmenta tus morosos, envía mensajes personalizados según su perfil y momento del proceso, recuperando 30% más cartera.','intermedio','4 horas','+30% recuperación',ARRAY['WhatsApp','OpenAI'],'Wallet',false),

-- OPERACIONES
('onboarding-clientes','Onboarding Automatizado de Clientes','operaciones','Email + tareas + recursos según perfil.','Cuando entra un cliente nuevo, la IA genera el plan de onboarding personalizado, programa emails, crea tareas en Asana y comparte recursos según su perfil.','intermedio','4 horas','−60% tiempo onboarding',ARRAY['OpenAI','Notion','Zapier'],'UserPlus',true),
('asistente-reuniones','Asistente de Reuniones (notas + tareas)','operaciones','Transcribe, resume, crea tareas.','Une la transcripción, el resumen y la creación de tareas en una sola pasada. Cada reunión termina con próximos pasos accionables en tu gestor de tareas.','principiante','2 horas','cero reuniones perdidas',ARRAY['Fireflies','OpenAI','Asana'],'CalendarCheck',false),
('sop-desde-video','Generador de SOPs desde Video','operaciones','Convierte un video en procedimiento documentado.','Subes un Loom mostrando un proceso y la IA te devuelve un SOP documentado con pasos, screenshots y mejores prácticas.','intermedio','3 horas','docs sin escribir',ARRAY['OpenAI','Loom'],'BookOpen',false),
('rutas-entrega','Optimizador de Rutas de Entrega','operaciones','IA reduce kilómetros recorridos.','La IA optimiza las rutas de tus repartidores en tiempo real considerando tráfico, prioridades y ventanas de entrega. Reduce 25% el costo logístico.','avanzado','1 día','−25% costo logístico',ARRAY['Google Maps API','OpenAI'],'Map',false),
('inventario-inteligente','Monitor de Inventario Inteligente','operaciones','Predice quiebres de stock.','La IA aprende tus patrones de venta y te alerta antes de que tengas un quiebre de stock, sugiriendo cantidades óptimas de reposición.','intermedio','4 horas','cero quiebres',ARRAY['OpenAI','Google Sheets'],'Package',false),
('compras-proveedores','Asistente de Compras Proveedores','operaciones','Compara cotizaciones y recomienda.','Envías 3 cotizaciones y la IA las compara línea por línea, identifica diferencias relevantes y recomienda la mejor opción con justificación.','principiante','2 horas','−15% costo de compra',ARRAY['OpenAI','Email'],'ShoppingCart',false),

-- RRHH
('screening-cvs','Screening Automático de CVs','rrhh','Ranking de candidatos por fit.','La IA lee todos los CVs recibidos, los rankea según el perfil que buscas y te entrega un shortlist con justificación. Reduce 80% el tiempo de screening.','intermedio','3 horas','−80% tiempo screening',ARRAY['OpenAI','Lever'],'Users',true),
('generador-jd','Generador de Job Descriptions','rrhh','JDs optimizados para tu cultura.','La IA genera job descriptions atractivos, inclusivos y optimizados para tu cultura empresarial en minutos.','principiante','1 hora','posts en minutos',ARRAY['OpenAI'],'ClipboardList',false),
('onboarding-empleados','Onboarding de Empleados con IA','rrhh','Plan personalizado primeros 90 días.','La IA genera el plan de los primeros 90 días personalizado según rol, equipo y nivel. Mejora retención early 40%.','intermedio','4 horas','+40% retención early',ARRAY['OpenAI','Notion'],'GraduationCap',false),
('performance-reviews','Asistente de Performance Reviews','rrhh','Genera feedback estructurado desde notas.','A partir de tus notas y feedback de pares, la IA genera reviews estructurados, objetivos y accionables.','principiante','2 horas','reviews objetivas y rápidas',ARRAY['OpenAI'],'Award',false),
('clima-laboral','Análisis de Clima Laboral','rrhh','Procesa encuestas anónimas y detecta patrones.','La IA procesa las respuestas abiertas de tus encuestas de clima, detecta temas recurrentes y te entrega insights por equipo y antigüedad.','intermedio','3 horas','cultura medida no asumida',ARRAY['Typeform','OpenAI'],'Heart',false),
('chatbot-rrhh','Chatbot Interno de RRHH','rrhh','Responde preguntas de empleados (vacaciones, beneficios).','Un chatbot en Slack que responde preguntas de empleados sobre vacaciones, beneficios, políticas y procesos. Reduce 70% los tickets a RRHH.','intermedio','4 horas','−70% tickets a RRHH',ARRAY['Slack','OpenAI'],'Bot',false);
